#!/usr/bin/env bash

case "$1" in
    # *.tar*) tar tf "$1";;
    # *.zip) unzip -l "$1";;
    # *.rar) unrar l "$1";;
    # *.7z) 7z l "$1";;
    *.tar*|*.tgz|*.zip|*.rar|*.7z) lsar "$1";;
    # *.pdf) pdftotext "$1" -;;
    *) bat --line-range=:500 "$1" || true;;
esac

