gui:
  expandFocusedSidePanel: true
  theme:
    lightTheme: false
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
      - bold
    selectedRangeBgColor:
      - blue

