" options {{{
set nocompatible

" encoding
set encoding=utf-8
set fileformats=unix,dos,mac

" user interface
set number
set relativenumber
set wildmenu
set wildignorecase
set wildignore=.git,.hg,.svn,.DS_Store,*~,*.o,*.out,*.pyc,**/tmp/**
set ruler
set showtabline=1
set cmdheight=2
set foldcolumn=1
set laststatus=2
"set statusline='\ %F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ %l,%c'
set statusline=%f\ %m%r%=%l,%-5v%p%%\ %{&fileencoding}\ %-4Y
set noshowmode
set shortmess=aoOtTIcF
set display=lastline
" turn off bell
set noerrorbells
set novisualbell
set t_vb=

" indentation
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set smartindent
set copyindent
set shiftwidth=4
set shiftround

" text
set showmatch
set matchtime=2
set nowrap
set virtualedit=block
set listchars=tab:▸\ ,trail:·,extends:›,nbsp:·
set list
set showbreak=›
set linebreak
set textwidth=120
set backspace=eol,start,indent
set whichwrap=<,>,[,],~
set cursorline
set nocursorcolumn
set colorcolumn=81
set scrolloff=10
set foldlevelstart=99

" searching
set ignorecase
set smartcase
set infercase
set incsearch
set hlsearch
set wrapscan
set magic
"set grepprg=

" timeout
set timeout
set timeoutlen=300
set ttimeout
set ttimeoutlen=0
set updatetime=100

" files && buffers
set autoread
set autowrite
set hidden
set nobackup
set nowritebackup
set noswapfile
set undofile
set undodir=$XDG_CACHE_HOME/vim/undo/
set viewdir=$XDG_CACHE_HOME/vim/view/
set spellfile=$HOME/.vim/spell/en.utf-8.add
set splitbelow
set splitright
set switchbuf=useopen

set complete=.,w,b,u,t,i,k
set completeopt=menuone,preview,noinsert

set history=2000
set lazyredraw

" }}}

" autocmd {{{
" auto detect file changes
au FocusGained,BufEnter * checktime

" close with q
au FileType help noremap <buffer><silent> q :close<cr>

" return to where you leave
au BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") | execute "normal! g'\"" | endif
" }}}

" commands {{{
" :W sudo save
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!
" }}}

" keymappings {{{
let mapleader = " "

" save&&quit
nnoremap <C-s> :w<cr>
noremap  <Leader>w :<C-u>w<cr>
nnoremap <C-q> <C-w>q
nnoremap Q     :qa<cr>
noremap  <Leader>q! :<C-u>qa!<cr>

" clear highlight
nnoremap <silent> <cr> :noh<cr>
vnoremap <silent> <cr> :<C-u>noh<cr>gv

" movement
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" move lines
nnoremap <silent> <A-j> :m .+1<CR>==
nnoremap <silent> <A-k> :m .-2<CR>==
vnoremap <silent> <A-j> :m '>+1<CR>gv=gv
vnoremap <silent> <A-k> :m '<-2<CR>gv=gv
inoremap <silent> <A-j> <Esc>:m .+1<CR>==gi
inoremap <silent> <A-k> <Esc>:m .-2<CR>==gi

" indent
vnoremap < <gv
vnoremap > >gv
vnoremap <S-Tab> <gv
vnoremap <Tab> >gv

" yank
nnoremap Y y$
vnoremap Y "+y

" reload vimrc
nnoremap <silent> <Leader>r :source $MYVIMRC<cr>

" }}}

source ~/.vim/plugins.vim
"colorscheme simple

" vim:foldmethod=marker:foldmarker={{{,}}}
