# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

[templates]
custom = '[[ ! -f $ZDOTDIR/plugins/{{ name }}.zsh ]] || source $ZDOTDIR/plugins/{{ name }}.zsh'
rename = '[[ -f {{ dir }}/{{ name }}.zsh ]] && cp {{ dir }}/{{ name }}.zsh {{ dir }}/_{{ name }}'

[plugins]

[plugins.preinit]
local = "~/.config/zsh/preinit"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
# proto = "ssh"
apply = ["source", "custom"]

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
# proto = "ssh"
use = [
    "lib/theme-and-appearance.zsh",
    "lib/completion.zsh",
    "lib/commpfix.zsh",
    "lib/clipboard.zsh",
    "lib/git.zsh",
    "lib/directories.zsh",
    "plugins/git/git.plugin.zsh",
    "plugins/colored-man-pages/colored-man-pages.plugin.zsh",
    # "plugins/sudo/sudo.plugin.zsh",
    ]

[plugins.zsh-vi-mode]
github = "jeffreytse/zsh-vi-mode"
# proto = "ssh"
apply = ["custom", "source"]

[plugins.fzf]
# github = "junegunn/fzf"
# proto = "ssh"
# apply = ["custom"]
local = "/usr/share/fzf"
use = ["*.zsh"]
apply = ["custom", "source"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
# proto = "ssh"
apply = ["source", "custom"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
# proto = "ssh"
use = ["{{ name }}.zsh"]
apply = ["custom", "source"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
# proto = "ssh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
# proto = "ssh"

[plugins."z.lua"]
github = "skywind3000/z.lua"
# proto = "ssh"
apply = ["custom", "source"]

## extra completions
#[plugins.sheldon]
#remote = "https://github.com/rossmacarthur/sheldon/raw/trunk/completions/sheldon.zsh"
#apply = ["fpath", "rename"]
#
#[plugins.exa]
#remote = "https://github.com/ogham/exa/raw/master/completions/zsh/_exa"
#apply = ["fpath"]
#
#[plugins.fd]
#remote = "https://github.com/sharkdp/fd/raw/master/contrib/completion/_fd"
#apply = ["fpath"]
##

[plugins.postinit]
local = "~/.config/zsh/postinit"
use = ["*.zsh"]

