#!/bin/bash
# ft - create new tmux session, or switch to existing one. Works from within tmux too. (@bag-man)
# `ft` will allow you to select your tmux session via fzf.
# `ft irc` will attach to the irc session (if it exists), else it will create it.

ft() {
  [[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
  if [ $1 ]; then
    tmux $change -t "$1" 2>/dev/null || (tmux new-session -d -s $1 && tmux $change -t "$1"); return
  fi
  session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) &&  tmux $change -t "$session" || echo "No sessions found."
}

ft "$@"
