[manager]
prepend_keymap = [
    { on = ["g", "v"], run = "cd ~/.config/nvim", desc = "Go ~/.config/nvim"},

    { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file"},
]
