[manager]
prepend_keymap = [
    { on = "q",     run = "quit --no-cwd-file",  desc = "Quit without outputting cwd-file" },
    { on = "Q",     run = "quit",                desc = "Quit the process" },
    { on = "<C-c>", run = "close --no-cwd-file", desc = "Close the current tab, or quit if it's last" },

    { on = ["g", "v"], run = "cd ~/.config/nvim", desc = "Go ~/.config/nvim"},
]
