format = """
$username$hostname$directory\
$git_branch$git_commit$git_state$git_status\
$fill \
$python\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"

[directory]
truncation_length = 5
truncation_symbol = "…/"
before_repo_root_style = "bright-black"
repo_root_style = "bold blue"
style = "blue"

[fill]
symbol = "·"
style = "black"

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "green"

[git_commit]
tag_symbol = "笠 "
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "green"

[git_status]
format = '([$all_status$ahead_behind]($style) ) '
style = "yellow"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '[${symbol}]($style)[${pyenv_prefix}(${version} )(\($virtualenv\) )]()'
symbol = ' '
